name: neovim-config
type: shell
commands: 
- git clone https://github.com/LazyVim/starter /etc/skel/.config/nvim
- cp /neovim/.nvimrc /etc/skel/.nvimrc
- cp -r /neovim/.config/nvim /etc/skel/.config/nvim
- rm -rf /neovim
