name: gnome-config
type: shell
commands:
- echo Configuring Gnome
- mkdir -p /etc/skel/Pictures
- wget -O /etc/skel/Pictures/tokyonight.jpg "https://unsplash.com/photos/H4uGE2skayY/download?ixid=M3wxMjA3fDB8MXxhbGx8fHx8fHx8fHwxNzMwNTUyMDQ5fA&force=true"
plugins:
- name: gnome-config-req
  type: apt
  sources:
    packages:
    - wget
