name: gnome-config
type: shell
commands:
- echo Configuring Gnome
- cp -rf /gnome/etc/skel/. /etc/skel/
- cp -rf /gnome/etc/dconf/. /etc/dconf/
- chmod +x /etc/skel/.local/share/vib/first-login.sh
- dconf update
- mkdir -p /etc/skel/Pictures
- wget -O /etc/skel/Pictures/tokyonight.jpg "https://unsplash.com/photos/H4uGE2skayY/download?ixid=M3wxMjA3fDB8MXxhbGx8fHx8fHx8fHwxNzMwNTUyMDQ5fA&force=true"
- cp /etc/skel/Pictures/tokyonight.jpg /usr/share/backgrounds/tokyonight.jpg
- tar -xzf /gnome/Colorful-Dark-Icons.tar.gz -C /usr/share/icons/
- gtk-update-icon-cache -f /usr/share/icons/Colorful-Dark-Icons || true
- rm -rf /gnome
plugins:
- name: gnome-config-req
  type: apt
  source:
    packages:
    - wget
