name: zsh-config
type: shell
commands:
# Set working dir
- mkdir -p /tmp/shell/
- cd /tmp/shell/
# Copy structure of /etc/skel
- mkdir -p /etc/skel/
- cp -rf /shell/etc/skel /etc/skel
# Oh my posh installation
- curl -s https://ohmyposh.dev/install.sh | bash -s -- -d /usr/local/bin
# oh-my-posh configuration
- mkdir -p /etc/skel/.config/zsh/oh-my-posh/themes
- cp -r /root/.cache/oh-my-posh/themes /etc/skel/.config/zsh/oh-my-posh/themes
# Install Prezto
- git clone --recursive https://github.com/sorin-ionescu/prezto.git /etc/skel/.config/zsh/.zprezto
# Install zpm-zsh ls plugin
- cd /etc/skel/.config/zsh/.zprezto
# Improved ls commands
- git submodule add https://github.com/zpm-zsh/ls.git modules/ls
# Replace ls with eza:
- git submodule add https://github.com/z-shell/zsh-eza.git
# zcolors
- git submodule add https://github.com/marlonrichert/zcolors.git modules/zcolors
# zsh-help
- git submodule add https://github.com/Freed-Wu/zsh-help.git modules/zsh-help
# Download all plugins
- git submodule update --init --recursive
- cd /tmp/shell/
# Install eza tokyonight theme
- git clone https://github.com/eza-community/eza-themes.git /tmp/shell/eza-themes
- mkdir -p /etc/skel/.config/eza
- cp /tmp/shell/eza-themes/themes/tokyonight.yml /etc/skel/.config/eza/theme.yml
- rm -rf /shell
- rm -rf /tmp/shell